## Template per applicare REGEX su Pandas

<img src='https://frenzy86.s3.eu-west-2.amazonaws.com/python/regex.jpg'>

In [5]:
import pandas as pd

import warnings
warnings.filterwarnings('ignore')

data = {'Text': ["Hello, gargamella doggy don't 123 @!£$%' \''s    \n hi", "456 World!", "789 doggy IFOAloveU"," ciao http://www.google.com"]}
df = pd.DataFrame(data)
df

                                                Text
0  Hello, gargamella doggy don't 123 @!£$%' ''s  ...
1                                         456 World!
2                                789 doggy IFOAloveU
3                         ciao http://www.google.com

In [9]:
# Definisci i pattern della REGEX
df = pd.DataFrame(data)

patterns = {
            r'\s+': ' ',            # prima e dopo come ultima sostituisce tutti i multipli spazi con uno spazio
            #r'......': '',          
            #r'......': '',         #aggiungere nuove regex qui
            r'\d+': '',             # remove digits (numeri)
            r'[^\w\s]': '',         # remove punteggiatura e simboli ...,'@!£$%
            r'\b\w{1,2}\b':'',      # remove all token less than2 characters
            r'(http|www)[^\s]+':'', # remove website
            r'\s+': ' '             # sostituisce tutti i multipli spazi con uno spazio
            }

words_to_remove = ['gargamella', 'doggy', 'word3']  # List of words to remove

# Add a new pattern to remove specific words
word_pattern = r'\b(?:{})\b'.format('|'.join(words_to_remove))
patterns[word_pattern] = ''

def clean_column(df, column, patterns):
    for pattern, replacement in patterns.items():
        df[column] = df[column].str.replace(pattern, replacement)
        df[column] = df[column].str.lower() # applica il lower
    return df

#solo in preview
clean_column(df, 'Text', patterns)

               Text
0  hello   dont
1             world
2         ifoaloveu
3             ciao

In [10]:
#applichiamo la modifica
df = clean_column(df, 'Text', patterns)
df

          Text
0  hello dont
1        world
2    ifoaloveu
3        ciao